const ENUMS = {
	inProgress: "IN_PROGRESS",
	// userRoles: {
	// 	LENDER: "LENDER",
	// 	ORG_OFFICIAL: "ORG_OFFICIAL", 
	// 	BORROWER: "BORROWER"
	// },
	userStates: {
		SIGNUP: "SIGNUP",
		REGISTERED: "REGISTERED",
		CONFIRMED: "CONFIRMED",
		SUBSCRIBED: "SUBSCRIBED",
		// BAGGED: 'BAGGED',
		// BUYAGREED: 'BUYAGREED',
		// SELLAGREED: 'SELLAGREED',
		APPLIED: "APPLIED",
	},
	ussdStates: {
		NULL: null,
		WELCOME: "WELCOME",
		REGISTER: "REGISTER",
		CONFIRM: "CONFIRM",
		SUBSCRIBE: "SUBSCRIBE",
		BAG: "BAG",
		BUYAGREE: "BUYAGREE",
		SELLAGREE: "SELLAGREE",
		APPLY: "APPLY",
		APPLY_CON: "APPLY_CON"
	},
	OTPTypes: {
		REG: "REG"
	}
};

module.exports = ENUMS;